/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 90608
 Source Host           : localhost:5432
 Source Catalog        : postgres
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 90608
 File Encoding         : 65001

 Date: 16/04/2018 15:14:30
*/


-- ----------------------------
-- Table structure for FORM_ENTRY_FIELD
-- ----------------------------
DROP TABLE IF EXISTS "public"."FORM_ENTRY_FIELD";
CREATE TABLE "public"."FORM_ENTRY_FIELD" (
  "ID" int4 NOT NULL DEFAULT nextval('"FORM_ENTRY_FIELD_ID_seq"'::regclass),
  "SC" text COLLATE "pg_catalog"."default",
  "IWO" text COLLATE "pg_catalog"."default",
  "SPK" text COLLATE "pg_catalog"."default",
  "VOY" text COLLATE "pg_catalog"."default",
  "AREA" text COLLATE "pg_catalog"."default",
  "SUPPLIER" text COLLATE "pg_catalog"."default",
  "BUYER" text COLLATE "pg_catalog"."default",
  "SELLER" text COLLATE "pg_catalog"."default",
  "TRADER" text COLLATE "pg_catalog"."default",
  "KONTRAK" text COLLATE "pg_catalog"."default",
  "PRODUCT" text COLLATE "pg_catalog"."default",
  "DATE_NOR" date,
  "TIME_NOR" time(6),
  "FWAL_BBLS" text COLLATE "pg_catalog"."default",
  "FWAL_KL15" text COLLATE "pg_catalog"."default",
  "FILE_ORDER" text COLLATE "pg_catalog"."default",
  "FWAL_KLOBS" text COLLATE "pg_catalog"."default",
  "REMARKS_NOR" text COLLATE "pg_catalog"."default",
  "SELECT_PORT" text COLLATE "pg_catalog"."default",
  "SHARING_FEE" text COLLATE "pg_catalog"."default",
  "SL_GSV_BBLS" text COLLATE "pg_catalog"."default",
  "SL_GSV_KL15" text COLLATE "pg_catalog"."default",
  "DATE_BERTHED" date,
  "FWAL_LONGTON" text COLLATE "pg_catalog"."default",
  "PRODUCT_TYPE" text COLLATE "pg_catalog"."default",
  "SELECT_CARGO" text COLLATE "pg_catalog"."default",
  "SL_GSV_KLOBS" text COLLATE "pg_catalog"."default",
  "TIME_BERTHED" time(6),
  "BL_START_DATE" date,
  "BL_START_TIME" time(6),
  "DATE_ACCEPTED" date,
  "DATE_CONTRACT" date,
  "PORT_TERMINAL" text COLLATE "pg_catalog"."default",
  "SAMPLE_SOURCE" text COLLATE "pg_catalog"."default",
  "SELECT_CLIENT" text COLLATE "pg_catalog"."default",
  "SFAL_TOV_BBLS" text COLLATE "pg_catalog"."default",
  "SFAL_TOV_KL15" text COLLATE "pg_catalog"."default",
  "ST_NOMINATION" text COLLATE "pg_catalog"."default",
  "TIME_ACCEPTED" time(6),
  "DATE_COMMENCED" date,
  "DATE_COMPLETED" date,
  "FWAL_METRICTON" text COLLATE "pg_catalog"."default",
  "SELECT_PRODUCT" text COLLATE "pg_catalog"."default",
  "SFAL_TOV_KLOBS" text COLLATE "pg_catalog"."default",
  "SL_GSV_LONGTON" text COLLATE "pg_catalog"."default",
  "TIME_COMMENCED" time(6),
  "TIME_COMPLETED" time(6),
  "DATE_ANCHORAGED" date,
  "REMARKS_BERTHED" text COLLATE "pg_catalog"."default",
  "RN_LETTER_ISSUE" text COLLATE "pg_catalog"."default",
  "RN_NOTICE_ISSUE" text COLLATE "pg_catalog"."default",
  "TIME_ANCHORAGED" time(6),
  "BL_QUANTITY_BBLS" text COLLATE "pg_catalog"."default",
  "BL_QUANTITY_KL15" text COLLATE "pg_catalog"."default",
  "DATE_KEY_MEETING" date,
  "DATE_OF_ANALYSIS" date,
  "REMARKS_ACCEPTED" text COLLATE "pg_catalog"."default",
  "SF_QUANTITY_BBLS" text COLLATE "pg_catalog"."default",
  "SF_QUANTITY_KL15" text COLLATE "pg_catalog"."default",
  "SFAL_TOV_LONGTON" text COLLATE "pg_catalog"."default",
  "SL_GSV_METRICTON" text COLLATE "pg_catalog"."default",
  "TIME_KEY_MEETING" time(6),
  "VEF_LOADING_BBLS" text COLLATE "pg_catalog"."default",
  "BL_QUANTITY_KLOBS" text COLLATE "pg_catalog"."default",
  "BO_MDO_ON_ARRIVAL" text COLLATE "pg_catalog"."default",
  "BO_MFO_ON_ARRIVAL" text COLLATE "pg_catalog"."default",
  "OBQ_QUANTITY_BBLS" text COLLATE "pg_catalog"."default",
  "OBQ_QUANTITY_KL15" text COLLATE "pg_catalog"."default",
  "REMARKS_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_COMPLETED" text COLLATE "pg_catalog"."default",
  "SF_QUANTITY_KLOBS" text COLLATE "pg_catalog"."default",
  "SL_VS_BOL_R1_BBLS" text COLLATE "pg_catalog"."default",
  "SL_VS_BOL_R1_KL15" text COLLATE "pg_catalog"."default",
  "ACTIVITIES_REMARKS" text COLLATE "pg_catalog"."default",
  "DATE_LOISPKPOWONOA" date,
  "DATE_VESSEL_SAILED" date,
  "LOADING_START_DATE" date,
  "LOADING_START_TIME" time(6),
  "OBQ_QUANTITY_KLOBS" text COLLATE "pg_catalog"."default",
  "REMARKS_ANCHORAGED" text COLLATE "pg_catalog"."default",
  "RN_STATEMENT_ISSUE" text COLLATE "pg_catalog"."default",
  "SFAL_TOV_METRICTON" text COLLATE "pg_catalog"."default",
  "SL_VS_BOL_R1_KLOBS" text COLLATE "pg_catalog"."default",
  "TIME_VESSEL_SAILED" time(6),
  "BL_QUANTITY_LONGTON" text COLLATE "pg_catalog"."default",
  "BO_MDO_ON_DEPARTURE" text COLLATE "pg_catalog"."default",
  "BO_MFO_ON_DEPARTURE" text COLLATE "pg_catalog"."default",
  "CLIENT_SITE_ID_FORM" text COLLATE "pg_catalog"."default",
  "DATE_HOSE_CONNECTED" date,
  "DATE_VESSEL_ARRIVED" date,
  "REMARKS_KEY_MEETING" text COLLATE "pg_catalog"."default",
  "SELECT_INTERVENTION" int4,
  "SF_QUANTITY_LONGTON" text COLLATE "pg_catalog"."default",
  "TIME_HOSE_CONNECTED" time(6),
  "TIME_VESSEL_ARRIVED" time(6),
  "DISCHARGE_START_DATE" date,
  "DISCHARGE_START_TIME" time(6),
  "OBQ_QUANTITY_LONGTON" text COLLATE "pg_catalog"."default",
  "SL_APPLIED_VEFL_BBLS" text COLLATE "pg_catalog"."default",
  "SL_VS_BOL_R1_LONGTON" text COLLATE "pg_catalog"."default",
  "BL_15_DERAJAT_CELCIUS" text COLLATE "pg_catalog"."default",
  "BL_QUANTITY_METRICTON" text COLLATE "pg_catalog"."default",
  "LOADING_COMPLETE_DATE" date,
  "LOADING_COMPLETE_TIME" time(6),
  "REMARKS_VESSEL_SAILED" text COLLATE "pg_catalog"."default",
  "DATE_DOCUMENTS_ONBOARD" date,
  "DATE_LOADING_COMMENCED" date,
  "DATE_LOADING_COMPLETED" date,
  "DATE_SURVEYOR_ON_BOARD" date,
  "OBQ_QUANTITY_METRICTON" text COLLATE "pg_catalog"."default",
  "REMARKS_HOSE_CONNECTED" text COLLATE "pg_catalog"."default",
  "REMARKS_VESSEL_ARRIVED" text COLLATE "pg_catalog"."default",
  "SF_QUANTITY_METRICTON" text COLLATE "pg_catalog"."default",
  "SL_VS_BOL_R1_METRICTON" text COLLATE "pg_catalog"."default",
  "TIME_DOCUMENTS_ONBOARD" time(6),
  "TIME_LOADING_COMMENCED" time(6),
  "TIME_LOADING_COMPLETED" time(6),
  "TIME_SURVEYOR_ON_BOARD" time(6),
  "DATE_SAMPLING_COMMENCED" date,
  "DATE_SAMPLING_COMPLETED" date,
  "DISCHARGE_COMPLETE_DATE" date,
  "DISCHARGE_COMPLETE_TIME" time(6),
  "SC_ON_ARRIVAL_DRAFT_AFT" text COLLATE "pg_catalog"."default",
  "SC_ON_ARRIVAL_DRAFT_FWD" text COLLATE "pg_catalog"."default",
  "TIME_SAMPLING_COMMENCED" time(6),
  "TIME_SAMPLING_COMPLETED" time(6),
  "DATE_CONNECTED_COMMENCED" date,
  "DATE_CONNECTED_COMPLETED" date,
  "SC_ON_ARRIVAL_DRAFT_LIST" text COLLATE "pg_catalog"."default",
  "TIME_CONNECTED_COMMENCED" time(6),
  "TIME_CONNECTED_COMPLETED" time(6),
  "REMARKS_DOCUMENTS_ONBOARD" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_COMPLETED" text COLLATE "pg_catalog"."default",
  "REMARKS_SURVEYOR_ON_BOARD" text COLLATE "pg_catalog"."default",
  "SC_ON_DEPARTURE_DRAFT_AFT" text COLLATE "pg_catalog"."default",
  "SC_ON_DEPARTURE_DRAFT_FWD" text COLLATE "pg_catalog"."default",
  "DATE_MEASUREMENT_COMMENCED" date,
  "DATE_MEASUREMENT_COMPLETED" date,
  "REMARKS_SAMPLING_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_SAMPLING_COMPLETED" text COLLATE "pg_catalog"."default",
  "SC_ON_DEPARTURE_DRAFT_LIST" text COLLATE "pg_catalog"."default",
  "SL_VEF_APPLIED_VS_BOL_BBLS" text COLLATE "pg_catalog"."default",
  "SL_VEF_APPLIED_VS_BOL_KL15" text COLLATE "pg_catalog"."default",
  "TIME_MEASUREMENT_COMMENCED" time(6),
  "TIME_MEASUREMENT_COMPLETED" time(6),
  "REMARKS_CONNECTED_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_CONNECTED_COMPLETED" text COLLATE "pg_catalog"."default",
  "SL_VEF_APPLIED_VS_BOL_KLOBS" text COLLATE "pg_catalog"."default",
  "REMARKS_MEASUREMENT_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_MEASUREMENT_COMPLETED" text COLLATE "pg_catalog"."default",
  "SL_VEF_APPLIED_VS_BOL_LONGTON" text COLLATE "pg_catalog"."default",
  "SL_VEF_APPLIED_VS_BOL_METRICTON" text COLLATE "pg_catalog"."default",
  "IS_DELETE" int4,
  "CREATE_TIME" timestamp(6),
  "CREATE_USER" text COLLATE "pg_catalog"."default",
  "MODIFY_TIME" timestamp(6),
  "MODIFY_USER" text COLLATE "pg_catalog"."default",
  "DELETE_TIME" timestamp(6),
  "CLIENT_SITE_ID" int4,
  "SF_GSV_KLOBS" text COLLATE "pg_catalog"."default",
  "SF_NSV_KLOBS" text COLLATE "pg_catalog"."default",
  "SF_FREE_WATER_AL_BBLS" text COLLATE "pg_catalog"."default",
  "SF_FREE_WATER_AL_KL15" text COLLATE "pg_catalog"."default",
  "SF_SFAL_TOV_METRICTON" text COLLATE "pg_catalog"."default",
  "SL_APPLIED_VEFL_KLOBS" text COLLATE "pg_catalog"."default",
  "DATE_HOSE_DISCONNECTED" date,
  "SF_FREE_WATER_AL_KLOBS" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_COMPLETED" date,
  "DATE_INPECTION_COMMENCED" date,
  "SF_FREE_WATER_AL_LONGTON" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_COMMENCED" time(6),
  "TIME_DISCHARGE_COMPLETED" time(6),
  "TIME_INPECTION_COMMENCED" time(6),
  "DATE_INSPECTION_COMPLETED" date,
  "REMARKS_HOSE_DISCONNECTED" text COLLATE "pg_catalog"."default",
  "SL_APPLIED_VEFL_METRICTON" text COLLATE "pg_catalog"."default",
  "TIME_INSPECTION_COMPLETED" time(6),
  "SF_FREE_WATER_AL_METRICTON" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_COMPLETED" text COLLATE "pg_catalog"."default",
  "REMARKS_INPECTION_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_INSPECTION_COMPLETED" text COLLATE "pg_catalog"."default",
  "DATE_HOSE_CONNECTED_COMMENCED" date,
  "DATE_HOSE_CONNECTED_COMPLETED" date,
  "SL_VEF_APPLIED_VS_BOL_R1_BBLS" text COLLATE "pg_catalog"."default",
  "SL_VEF_APPLIED_VS_BOL_R1_KL15" text COLLATE "pg_catalog"."default",
  "TIME_HOSE_CONNECTED_COMMENCED" time(6),
  "TIME_HOSE_CONNECTED_COMPLETED" time(6),
  "SL_VEF_APPLIED_VS_BOL_R1_KLOBS" text COLLATE "pg_catalog"."default",
  "SF_SHORE_TANKS_NOMINATION_KLOBS" text COLLATE "pg_catalog"."default",
  "DATE_CARGO_MEASUREMENT_COMMENCED" date,
  "DATE_CARGO_MEASUREMENT_COMPLETED" date,
  "REMARKS_HOSE_CONNECTED_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_HOSE_CONNECTED_COMPLETED" text COLLATE "pg_catalog"."default",
  "SL_VEF_APPLIED_VS_BOL_R1_LONGTON" text COLLATE "pg_catalog"."default",
  "TIME_CARGO_MEASUREMENT_COMMENCED" time(6),
  "TIME_CARGO_MEASUREMENT_COMPLETED" time(6),
  "SL_VEF_APPLIED_VS_BOL_R1_METRICTON" text COLLATE "pg_catalog"."default",
  "REMARKS_CARGO_MEASUREMENT_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_CARGO_MEASUREMENT_COMPLETED" text COLLATE "pg_catalog"."default",
  "BL_FLOW_METER" text COLLATE "pg_catalog"."default",
  "BL_SHORE_TANK" text COLLATE "pg_catalog"."default",
  "BL_SHIP_TANK" text COLLATE "pg_catalog"."default",
  "FSOQ" text COLLATE "pg_catalog"."default",
  "SURVEYOR_IN_CHARGE" text COLLATE "pg_catalog"."default",
  "RN_NOTICE_ISSUE_DESCRIPTION" text COLLATE "pg_catalog"."default",
  "RN_LETTER_ISSUE_DESCRIPTION" text COLLATE "pg_catalog"."default",
  "RN_STATEMENT_ISSUE_DESCRIPTION" text COLLATE "pg_catalog"."default",
  "DATE_A_AWEIGH" date,
  "TIME_A_AWEIGH" time(6),
  "DATE_POB" date,
  "TIME_POB" time(6),
  "DATE_BERTHING" date,
  "TIME_BERTHING" time(6),
  "DATE_SBD_COMMENCED" date,
  "DATE_SBD_COMPLETED" date,
  "TIME_SBD_COMMENCED" time(6),
  "TIME_SBD_COMPLETED" time(6),
  "DATE_DISCHARGE_COMMENCED" date,
  "DATE_TANKS_INS_COMMENCED" date,
  "TIME_TANKS_INS_COMMENCED" time(6),
  "DATE_TANKS_INS_COMPLETED" date,
  "TIME_TANKS_INS_COMPLETED" time(6),
  "DATE_SVY_LEFT_VESSEL" date,
  "TIME_SVY_LEFT_VESSEL" time(6),
  "DATE_VESSEL_SAIL" date,
  "TIME_VESSEL_SAIL" time(6),
  "TIME_HOSE_DISCONNECTED" time(6),
  "BL_SFAL_KL15" text COLLATE "pg_catalog"."default",
  "BL_SFAL_BBLS" text COLLATE "pg_catalog"."default",
  "BL_SFAL_METRICTON" text COLLATE "pg_catalog"."default",
  "BL_SFAL_LONGTON" text COLLATE "pg_catalog"."default",
  "SF_SFAL_KLOBS" text COLLATE "pg_catalog"."default",
  "SF_SFAL_KL15" text COLLATE "pg_catalog"."default",
  "SF_SFAL_BBLS" text COLLATE "pg_catalog"."default",
  "SF_SFAL_METRICTON" text COLLATE "pg_catalog"."default",
  "SF_SFAL_LONGTON" text COLLATE "pg_catalog"."default",
  "SFBD_TOV_KLOBS" text COLLATE "pg_catalog"."default",
  "SFBD_TOV_KL15" text COLLATE "pg_catalog"."default",
  "SFBD_TOV_BBLS" text COLLATE "pg_catalog"."default",
  "SFBD_TOV_METRICTON" text COLLATE "pg_catalog"."default",
  "SFBD_TOV_LONGTON" text COLLATE "pg_catalog"."default",
  "SFBD_GSV_KLOBS" text COLLATE "pg_catalog"."default",
  "SFBD_GSV_BBLS" text COLLATE "pg_catalog"."default",
  "SFBD_GSV_METRICTON" text COLLATE "pg_catalog"."default",
  "SFBD_GSV_LONGTON" text COLLATE "pg_catalog"."default",
  "ROBQ_KLOBS" text COLLATE "pg_catalog"."default",
  "ROBQ_KL15" text COLLATE "pg_catalog"."default",
  "ROBQ_BBLS" text COLLATE "pg_catalog"."default",
  "ROBQ_METRICTON" text COLLATE "pg_catalog"."default",
  "ROBQ_LONGTON" text COLLATE "pg_catalog"."default",
  "BL_SFAL_KLOBS" text COLLATE "pg_catalog"."default",
  "SFBD_GSV_KL15" text COLLATE "pg_catalog"."default",
  "SLVS_BOL_R1_KLOBS" text COLLATE "pg_catalog"."default",
  "SLVS_BOL_R1_KL15" text COLLATE "pg_catalog"."default",
  "SLVS_BOL_R1_BBLS" text COLLATE "pg_catalog"."default",
  "SLVS_BOL_R1_LONGTON" text COLLATE "pg_catalog"."default",
  "SLVS_BOL_R1_METRICTON" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SFBD_R2_KLOBS" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SFBD_R2_KL15" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SFBD_R2_BBLS" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SFBD_R2_LONGTON" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SFBD_R2_METRICTON" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_R3_KLOBS" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_R3_KL15" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_R3_BBLS" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_R3_LONGTON" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_R3_METRICTON" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_R4_KLOBS" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_R4_KL15" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_R4_BBLS" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_R4_LONGTON" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_R4_METRICTON" text COLLATE "pg_catalog"."default",
  "VESSEL" text COLLATE "pg_catalog"."default",
  "ALERT_PUSH" int4 DEFAULT 0,
  "CLIENTS" text COLLATE "pg_catalog"."default",
  "BL_GSV_KLOBS" text COLLATE "pg_catalog"."default",
  "BL_GSV_KL15" text COLLATE "pg_catalog"."default",
  "BL_GSV_BBLS" text COLLATE "pg_catalog"."default",
  "BL_GSV_LONGTON" text COLLATE "pg_catalog"."default",
  "BL_GSV_METRICTON" text COLLATE "pg_catalog"."default",
  "BL_NSV_KLOBS" text COLLATE "pg_catalog"."default",
  "BL_NSV_KL15" text COLLATE "pg_catalog"."default",
  "BL_NSV_BBLS" text COLLATE "pg_catalog"."default",
  "BL_NSV_LONGTON" text COLLATE "pg_catalog"."default",
  "BL_NSV_METRICTON" text COLLATE "pg_catalog"."default",
  "SF_GSV_KL15" text COLLATE "pg_catalog"."default",
  "SF_GSV_BBLS" text COLLATE "pg_catalog"."default",
  "SF_GSV_LONGTON" text COLLATE "pg_catalog"."default",
  "SF_GSV_METRICTON" text COLLATE "pg_catalog"."default",
  "SF_NSV_KL15" text COLLATE "pg_catalog"."default",
  "SF_NSV_BBLS" text COLLATE "pg_catalog"."default",
  "SF_NSV_LONGTON" text COLLATE "pg_catalog"."default",
  "SF_NSV_METRICTON" text COLLATE "pg_catalog"."default",
  "SF_SFAL_TOV_KLOBS" text COLLATE "pg_catalog"."default",
  "SF_SFAL_TOV_KL15" text COLLATE "pg_catalog"."default",
  "SF_SFAL_TOV_BBLS" text COLLATE "pg_catalog"."default",
  "SF_SFAL_TOV_LONGTON" text COLLATE "pg_catalog"."default",
  "SFAL_GSV_KLOBS" text COLLATE "pg_catalog"."default",
  "SFAL_GSV_KL15" text COLLATE "pg_catalog"."default",
  "SFAL_GSV_BBLS" text COLLATE "pg_catalog"."default",
  "SFAL_GSV_LONGTON" text COLLATE "pg_catalog"."default",
  "SFAL_GSV_METRICTON" text COLLATE "pg_catalog"."default",
  "SFAL_NSV_KLOBS" text COLLATE "pg_catalog"."default",
  "SFAL_NSV_KL15" text COLLATE "pg_catalog"."default",
  "SFAL_NSV_BBLS" text COLLATE "pg_catalog"."default",
  "SFAL_NSV_LONGTON" text COLLATE "pg_catalog"."default",
  "SFAL_NSV_METRICTON" text COLLATE "pg_catalog"."default",
  "VEFL_KLOBS" text COLLATE "pg_catalog"."default",
  "VEFL_KL15" text COLLATE "pg_catalog"."default",
  "VEFL_BBLS" text COLLATE "pg_catalog"."default",
  "VEFL_LONGTON" text COLLATE "pg_catalog"."default",
  "VEFL_METRICTON" text COLLATE "pg_catalog"."default",
  "SL_APPLIED_VEFL_KL15" text COLLATE "pg_catalog"."default",
  "SL_APPLIED_VEFL_LONGTON" text COLLATE "pg_catalog"."default",
  "REMARKS_POB" text COLLATE "pg_catalog"."default",
  "REMARKS_A_AWEIGH" text COLLATE "pg_catalog"."default",
  "REMARKS_BERTHING" text COLLATE "pg_catalog"."default",
  "REMARKS_SBD_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_SBD_COMPLETED" text COLLATE "pg_catalog"."default",
  "REMARKS_TANKS_INS_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_TANKS_INS_COMPLETED" text COLLATE "pg_catalog"."default",
  "REMARKS_SVY_LEFT_VESSEL" text COLLATE "pg_catalog"."default",
  "REMARKS_VESSEL_SAIL" text COLLATE "pg_catalog"."default",
  "SFAL_KLOBS" text COLLATE "pg_catalog"."default",
  "SFAL_KL15" text COLLATE "pg_catalog"."default",
  "SFAL_BBLS" text COLLATE "pg_catalog"."default",
  "SFAL_LONGTON" text COLLATE "pg_catalog"."default",
  "SFAL_METRICTON" text COLLATE "pg_catalog"."default",
  "SF_SQ_KLOBS" text COLLATE "pg_catalog"."default",
  "SF_SQ_KL15" text COLLATE "pg_catalog"."default",
  "SF_SQ_BBLS" text COLLATE "pg_catalog"."default",
  "SF_SQ_LONGTON" text COLLATE "pg_catalog"."default",
  "SF_SQ_METRICTON" text COLLATE "pg_catalog"."default",
  "FREE_WATER_KLOBS" text COLLATE "pg_catalog"."default",
  "FREE_WATER_KL15" text COLLATE "pg_catalog"."default",
  "FREE_WATER_BBLS" text COLLATE "pg_catalog"."default",
  "FREE_WATER_LONGTON" text COLLATE "pg_catalog"."default",
  "FREE_WATER_METRICTON" text COLLATE "pg_catalog"."default",
  "SFBD_NSV_KLOBS" text COLLATE "pg_catalog"."default",
  "SFBD_NSV_KL15" text COLLATE "pg_catalog"."default",
  "SFBD_NSV_BBLS" text COLLATE "pg_catalog"."default",
  "SFBD_NSV_LONGTON" text COLLATE "pg_catalog"."default",
  "SFBD_NSV_METRICTON" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_BARGE_ARRIVED" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_BARGE_ARRIVED" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_BARGE_ARRIVED" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_NOR_TENDERED" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_NOR_TENDERED" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_NOR_TENDERED" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_BARGE_ALL_FAST_ALONGSIDE" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_BARGE_ALL_FAST_ALONGSIDE" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_BARGE_ALL_FAST_ALONGSIDE" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_KEY_MEETING" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_KEY_MEETING" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_KEY_MEETING" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_NOR_ACCEPTED" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_NOR_ACCEPTED" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_NOR_ACCEPTED" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_VALVE_SEEALED" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_VALVE_SEEALED" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_VALVE_SEEALED" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_TANK_INSPECT_METER_VERIFICATION" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_TANK_INSPECT_METER_VERIFICATION" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_TANK_INSPECT_METER_VERIFICATION" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_HOST_CONNECTED" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_HOST_CONNECTED" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_HOST_CONNECTED" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_LOADING_COMMENCED" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_LOADING_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_LOADING_COMMENCED" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_LOADING_COMPLETED" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_LOADING_COMPLETED" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_LOADING_COMPLETED" text COLLATE "pg_catalog"."default",
  "TIME_DATE_LOADING_HOSE_ARMS_DISCONNECT" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_HOSE_ARMS_DISCONNECT" text COLLATE "pg_catalog"."default",
  "REMARKS_DATE_LOADING_HOSE_ARMS_DISCONNECT" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_TANK_INSPECT_METER_VERIFICATION_FINAL" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_TANK_INSPECT_METER_VERIFICATION_FINAL" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_TANK_INSPECT_METER_VERIFICATION_FINAL" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_CALCUL_COMPLETED_DOC_ONBOARD" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_CALCUL_COMPLETED_DOC_ONBOARD" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_CALCUL_COMPLETED_DOC_ONBOARD" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_BARGE_ARRIVED" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_BARGE_ARRIVED" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_BARGE_ARRIVED" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_NOR_TENDERED" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_NOR_TENDERED" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_NOR_TENDERED" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_KEY_MEETING" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_KEY_MEETING" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_KEY_MEETING" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_NOR_ACCEPTED" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_NOR_ACCEPTED" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_NOR_ACCEPTED" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_VALVE_SEEALED" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_VALVE_SEEALED" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_VALVE_SEEALED" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_TANK_INSPECT_MEASURE" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_TANK_INSPECT_MEASURE" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_TANK_INSPECT_MEASURE" text COLLATE "pg_catalog"."default",
  "TIME_VISUAL_INSPECTION_SAMPLING" text COLLATE "pg_catalog"."default",
  "DATE_VISUAL_INSPECTION_SAMPLING" text COLLATE "pg_catalog"."default",
  "REMARKS_VISUAL_INSPECTION_SAMPLING" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_HOST_CONNECTED" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_HOST_CONNECTED" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_HOST_CONNECTED" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_BUNKER_COMMENCED" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_BUNKER_COMMENCED" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_BUNKER_COMMENCED" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_BUNKER_COMPLETED" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_BUNKER_COMPLETED" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_BUNKER_COMPLETED" text COLLATE "pg_catalog"."default",
  "TIME_DATE_DISCHARGE_HOSE_DISCONNECT" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_HOSE_DISCONNECT" text COLLATE "pg_catalog"."default",
  "REMARKS_DATE_DISCHARGE_HOSE_DISCONNECT" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_TANK_INSPECT_MEASR_FINAL" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_TANK_INSPECT_MEASR_FINAL" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_TANK_INSPECT_MEASR_FINAL" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_VISUAL_INSPECTION_SAMPLING" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_VISUAL_INSPECTION_SAMPLING" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_VISUAL_INSPECTION_SAMPLING" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_CALCUL_COMPLETED_DOC_ONBOARD" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_CALCUL_COMPLETED_DOC_ONBOARD" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_CALCUL_COMPLETED_DOC_ONBOARD" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_BARGE_LEAVE_SHIP" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_BARGE_LEAVE_SHIP" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_BARGE_LEAVE_SHIP" text COLLATE "pg_catalog"."default",
  "INITIAL_READOUT_KLOBS" text COLLATE "pg_catalog"."default",
  "INITIAL_READOUT_KL15" text COLLATE "pg_catalog"."default",
  "INITIAL_READOUT_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "FINAL_READOUT_KLOBS" text COLLATE "pg_catalog"."default",
  "FINAL_READOUT_KL15" text COLLATE "pg_catalog"."default",
  "FINAL_READOUT_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "DIFFERENCE_KLOBS" text COLLATE "pg_catalog"."default",
  "DIFFERENCE_KL15" text COLLATE "pg_catalog"."default",
  "DIFFERENCE_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "METER_FACTOR_KLOBS" text COLLATE "pg_catalog"."default",
  "CORD_VOL_DELIVERED_KLOBS" text COLLATE "pg_catalog"."default",
  "CORD_VOL_DELIVERED_KL15" text COLLATE "pg_catalog"."default",
  "CORD_VOL_DELIVERED_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "DENSITY15DEG_KLOBS" text COLLATE "pg_catalog"."default",
  "SUPPLY_LOSS_KLOBS" text COLLATE "pg_catalog"."default",
  "SUPPLY_LOSS_KL15" text COLLATE "pg_catalog"."default",
  "SUPPLY_LOSS_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_TANK_INSPECT_MEASURE" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_TANK_INSPECT_MEASURE" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_TANK_INSPECT_MEASURE" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_TANK_INSPECT_METER_VERF" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_TANK_INSPECT_METER_VERF" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_TANK_INSPECT_METER_VERF" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_VISUAL_INSPEC_SAMPL" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_VISUAL_INSPEC_SAMPL" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_VISUAL_INSPEC_SAMPL" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_TANK_INSPECT_MEASR_FINAL" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_TANK_INSPECT_MEASR_FINAL" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_TANK_INSPECT_MEASR_FINAL" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_TANK_INSPECT_METER_FINAL" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_TANK_INSPECT_METER_FINAL" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_TANK_INSPECT_METER_FINAL" text COLLATE "pg_catalog"."default",
  "TIME_LOADING_BARGE_LEAVE_DEPOT" text COLLATE "pg_catalog"."default",
  "DATE_LOADING_BARGE_LEAVE_DEPOT" text COLLATE "pg_catalog"."default",
  "REMARKS_LOADING_BARGE_LEAVE_DEPOT" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_BARGE_ALL_FAST_ALONGSIDE" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_BARGE_ALL_FAST_ALONGSIDE" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_BARGE_ALL_FAST_ALONGSIDE" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_TANK_INSPECT_METER_VERF" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_TANK_INSPECT_METER_VERF" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_TANK_INSPECT_METER_VERF" text COLLATE "pg_catalog"."default",
  "TIME_DATE_DISCHARGE_HOSE_ARMS_DISCONNECT" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_HOSE_ARMS_DISCONNECT" text COLLATE "pg_catalog"."default",
  "REMARKS_DATE_DISCHARGE_HOSE_ARMS_DISCONNECT" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_VISUAL_INSPEC_SAMPL" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_VISUAL_INSPEC_SAMPL" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_VISUAL_INSPEC_SAMPL" text COLLATE "pg_catalog"."default",
  "TIME_DISCHARGE_TANK_INSPECT_METER_FINAL" text COLLATE "pg_catalog"."default",
  "DATE_DISCHARGE_TANK_INSPECT_METER_FINAL" text COLLATE "pg_catalog"."default",
  "REMARKS_DISCHARGE_TANK_INSPECT_METER_FINAL" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_LOADING_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_LOADING_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_LOADING_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_LOADING_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_LOADING_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_LOADING_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "BARGE_LOADED_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_LOADED_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_LOADED_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_DISCHARGE_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_DISCHARGE_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_DISCHARGE_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_DISCHARGE_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_DISCHARGE_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_DISCHARGE_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "BARGE_DISCHARGE_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_DISCHARGE_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_DISCHARGE_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_RECEIVE_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_RECEIVE_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_BEFORE_RECEIVE_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_RECEIVE_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_RECEIVE_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_AFTER_RECEIVE_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "BARGE_RECEIVE_KLOBS" text COLLATE "pg_catalog"."default",
  "BARGE_RECEIVE_KL15" text COLLATE "pg_catalog"."default",
  "BARGE_RECEIVE_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "LOADING_LOSS_R1_KLOBS" text COLLATE "pg_catalog"."default",
  "LOADING_LOSS_R1_KL15" text COLLATE "pg_catalog"."default",
  "LOADING_LOSS_R1_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "TRANSPORTATION_LOSS_R2_KLOBS" text COLLATE "pg_catalog"."default",
  "TRANSPORTATION_LOSS_R2_KL15" text COLLATE "pg_catalog"."default",
  "TRANSPORTATION_LOSS_R2_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "DISCHARGE_LOSS_R3_KLOBS" text COLLATE "pg_catalog"."default",
  "DISCHARGE_LOSS_R3_KL15" text COLLATE "pg_catalog"."default",
  "DISCHARGE_LOSS_R3_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "SUPPLY_LOSS_R4_KLOBS" text COLLATE "pg_catalog"."default",
  "SUPPLY_LOSS_R4_KL15" text COLLATE "pg_catalog"."default",
  "SUPPLY_LOSS_R4_METRIC_TONS" text COLLATE "pg_catalog"."default",
  "SF_QUANTITY_METRICTON	" text COLLATE "pg_catalog"."default",
  "SF_SHORE_RECEIVED_KLOBS" text COLLATE "pg_catalog"."default",
  "SF_SHORE_RECEIVED_KL15" text COLLATE "pg_catalog"."default",
  "SF_SHORE_RECEIVED_BBLS" text COLLATE "pg_catalog"."default",
  "SF_SHORE_RECEIVED_LONGTON" text COLLATE "pg_catalog"."default",
  "SF_SHORE_RECEIVED_METRICTON" text COLLATE "pg_catalog"."default",
  "SF_STU" text COLLATE "pg_catalog"."default",
  "SF_DENSITY_15C" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SF_KLOBS" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SF_KL15" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SF_BBLS" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SF_LONGTON" text COLLATE "pg_catalog"."default",
  "SFAL_VS_SF_METRICTON" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_KLOBS" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_KL15" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_BBLS" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_LONGTON" text COLLATE "pg_catalog"."default",
  "SFBD_VS_SR_METRICTON" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_KLOBS" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_KL15" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_BBLS" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_LONGTON" text COLLATE "pg_catalog"."default",
  "SR_VS_BOL_METRICTON" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of FORM_ENTRY_FIELD
-- ----------------------------
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (23, '', 'IWO/001', '["LOI\/001","LOI\/002"]', '["VOYAGE.001","VOY\/002"]', 'TANJUNG PRIUK', '["on"]', '["on"]', NULL, NULL, '["KONTRAK\/001","KONTRAK\/002"]', '["HSO"]', '2018-04-18', '00:00:00', NULL, NULL, 'FO/001', NULL, '', 'single_port', '["50","50"]', NULL, NULL, NULL, NULL, '', NULL, NULL, '00:00:00', '2018-04-18', '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, '2018-04-17', '', 'no', 'no', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '567', '543', NULL, NULL, NULL, '-Infinity', '-5.867256637168142', '', NULL, NULL, '2018-04-16', '00:00:00', '421', '', 'no', NULL, '-1.1849710982658959', '00:00:00', NULL, '100', '320', '', NULL, '2018-04-16', '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '421', '320', '0.2013888888888889', '765', NULL, '2018-04-20', '00:00:00', '', NULL, NULL, NULL, NULL, '654', NULL, '', NULL, '-3.022421524663677', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 10:31:07', NULL, NULL, 'admin', NULL, NULL, '65645', '432', '654', '344', '463', '230', NULL, '563', NULL, NULL, '876', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '112', NULL, NULL, '', '', NULL, NULL, '-Infinity', '-5.867256637168142', '00:00:00', '00:00:00', '-1.1849710982658959', '410', NULL, NULL, '', '', '0.2013888888888889', '00:00:00', '00:00:00', '-3.022421524663677', '', '', 'Y', NULL, NULL, NULL, '["AGUS","AGUS"]', '""', '""', '""', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PELNI001', 0, '["CLIENT001","KONTRAK\/002"]', '34', '4523', '233', '665', '7856', '756', '776', '765', '345', '897', '754', '654', '765', '345', '643', '563', '123', '190', '567', '765', '678', '786', '321', '543', '542', '432', '120', '346', '113', '', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (26, 'No Condition', 'IWO/001', '["LOI\/001","LOI\/002"]', '["VOYAGE\/001","VOY\/002"]', 'TANJUNG PRIUK', '["on"]', '["on"]', NULL, NULL, '["KONTRAK\/001","KONTRAK\/002"]', '["HSO"]', '2018-04-18', '00:00:00', NULL, NULL, 'FO/001', NULL, '', 'single_port', '["50","50"]', NULL, NULL, NULL, NULL, '', NULL, NULL, '00:00:00', '2018-04-18', '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, '2018-04-17', '', 'no', 'no', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '567', '543', NULL, NULL, NULL, '-Infinity', '-5.867256637168142', '', NULL, NULL, '2018-04-16', '00:00:00', '421', '', 'no', NULL, '-1.1849710982658959', '00:00:00', NULL, '100', '320', '', NULL, '2018-04-16', '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '421', '320', '0.2013888888888889', '765', NULL, '2018-04-20', '00:00:00', '', NULL, NULL, NULL, NULL, '654', NULL, '', NULL, '-3.022421524663677', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 10:50:31', NULL, NULL, 'admin', NULL, NULL, '65645', '432', '654', '344', '463', '230', NULL, '563', NULL, NULL, '876', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '112', NULL, NULL, '', '', NULL, NULL, '-Infinity', '-5.867256637168142', '00:00:00', '00:00:00', '-1.1849710982658959', '410', NULL, NULL, '', '', '0.2013888888888889', '00:00:00', '00:00:00', '-3.022421524663677', '', '', 'Y', NULL, NULL, NULL, '["AGUS","INDRA"]', '""', '""', '""', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PELNI001', 0, '["CLIENT001","KONTRAK\/002"]', '34', '4523', '233', '665', '7856', '756', '776', '765', '345', '897', '754', '654', '765', '345', '643', '563', '123', '190', '567', '765', '678', '786', '321', '543', '542', '432', '120', '346', '113', '', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (27, 'No Condition', 'IWO/001', '["LOI\/001","LOI\/002"]', '["VOYAGE\/001","VOY\/002"]', 'TANJUNG PRIUK', '["on"]', '["on"]', NULL, NULL, '["KONTRAK\/001","KONTRAK\/002"]', '["HSO"]', '2018-04-18', '00:00:00', NULL, NULL, 'FO/001', NULL, '', 'single_port', '["50","50"]', NULL, NULL, NULL, NULL, '', NULL, NULL, '00:00:00', '2018-04-18', '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, '2018-04-17', '', 'no', 'no', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '567', '543', NULL, NULL, NULL, '-5.954545454545454', '-5.867256637168142', '', NULL, NULL, '2018-04-16', '00:00:00', '421', '', 'no', NULL, '-1.1849710982658959', '00:00:00', NULL, '100', '320', '', NULL, '2018-04-16', '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '421', '320', '0.2013888888888889', '765', NULL, '2018-04-20', '00:00:00', '', NULL, NULL, NULL, NULL, '654', NULL, '', NULL, '-3.022421524663677', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 11:10:31', NULL, NULL, 'admin', NULL, NULL, '65645', '432', '654', '344', '463', '230', NULL, '563', NULL, NULL, '876', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '112', NULL, NULL, '', '', NULL, NULL, '-5.954545454545454', '-5.867256637168142', '00:00:00', '00:00:00', '-1.1849710982658959', '410', NULL, NULL, '', '', '0.2013888888888889', '00:00:00', '00:00:00', '-3.022421524663677', '', '', 'Y', NULL, NULL, NULL, '["AGUS","INDRA"]', '""', '""', '""', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PELNI001', 0, '["CLIENT001","KONTRAK\/002"]', '34', '4523', '233', '665', '7856', '756', '776', '765', '345', '897', '754', '654', '765', '345', '643', '563', '123', '190', '567', '765', '678', '786', '321', '543', '542', '432', '120', '346', '113', '110', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (25, 'No Condition', 'IWO/001', '["LOI\/001","LOI\/002"]', '["VOYAGE.001","VOY\/002"]', 'TANJUNG PRIUK', '["on"]', '["on"]', NULL, NULL, '["KONTRAK\/001","KONTRAK\/002"]', '["HSO"]', '2018-04-18', '00:00:00', NULL, NULL, 'FO/001', NULL, '', 'single_port', '["50","50"]', NULL, NULL, NULL, NULL, '', NULL, NULL, '00:00:00', '2018-04-18', '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, '2018-04-17', '', 'no', 'no', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '567', '543', NULL, NULL, NULL, '-Infinity', '-5.867256637168142', '', NULL, NULL, '1970-01-01', '00:00:00', '421', '', 'no', NULL, '-1.1849710982658959', '00:00:00', NULL, '100', '320', '', NULL, '2018-04-16', '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '421', '320', '0.2013888888888889', '765', NULL, '2018-04-20', '00:00:00', '', NULL, NULL, NULL, NULL, '654', NULL, '', NULL, '-3.022421524663677', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 10:42:56', NULL, NULL, 'admin', NULL, NULL, '65645', '432', '654', '344', '463', '230', NULL, '563', NULL, NULL, '876', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '112', NULL, NULL, '', '', NULL, NULL, '-Infinity', '-5.867256637168142', '00:00:00', '00:00:00', '-1.1849710982658959', '410', NULL, NULL, '', '', '0.2013888888888889', '00:00:00', '00:00:00', '-3.022421524663677', '', '', 'Y', NULL, NULL, NULL, '["AGUS","AGUS"]', '""', '""', '""', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PELNI001', 0, '["CLIENT001","KONTRAK\/002"]', '34', '4523', '233', '665', '7856', '756', '776', '765', '345', '897', '754', '654', '765', '345', '643', '563', '123', '190', '567', '765', '678', '786', '321', '543', '542', '432', '120', '346', '113', '', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (28, 'No Condition', 'IWO/001', '["LOI\/001","LOI\/002"]', '["VOYAGE\/001","VOY\/002"]', 'TANJUNG PRIUK', '["on"]', '["on"]', NULL, NULL, '["KONTRAK\/001","KONTRAK\/002"]', '["HSO"]', '2018-04-18', '00:00:00', NULL, NULL, 'FO/001', NULL, '', 'single_port', '["50","50"]', NULL, NULL, NULL, NULL, '', NULL, NULL, '00:00:00', '2018-04-18', '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, '2018-04-17', '', 'yes', 'yes', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '567', '543', NULL, NULL, NULL, '-5.954545454545454', '-5.867256637168142', '', NULL, NULL, '2018-04-16', '00:00:00', '421', '', 'yes', NULL, '-1.1849710982658959', '00:00:00', NULL, '100', '320', '', NULL, '2018-04-16', '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '421', '320', '0.2013888888888889', '765', NULL, '2018-04-20', '00:00:00', '', NULL, NULL, NULL, NULL, '654', NULL, '', NULL, '-3.022421524663677', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 11:17:24', NULL, NULL, 'admin', NULL, NULL, '65645', '432', '654', '344', '463', '230', NULL, '563', NULL, NULL, '876', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '112', NULL, NULL, '', '', NULL, NULL, '-5.954545454545454', '-5.867256637168142', '00:00:00', '00:00:00', '-1.1849710982658959', '410', NULL, NULL, '', '', '0.2013888888888889', '00:00:00', '00:00:00', '-3.022421524663677', '', '', 'Y', NULL, NULL, '["Penguins.jpg","Lighthouse1.jpg"]', '["AGUS","INDRA"]', '"Tulips1.jpg"', '"Chrysanthemum1.jpg"', '"Lighthouse2.jpg"', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PELNI001', 0, '["CLIENT001","KONTRAK\/002"]', '34', '4523', '233', '665', '7856', '756', '776', '765', '345', '897', '754', '654', '765', '345', '643', '563', '123', '190', '567', '765', '678', '786', '321', '543', '542', '432', '120', '346', '113', '110', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (29, 'No Condition', 'IWO/001', '["LOI\/001","LOI\/002"]', '["VOYAGE\/001","VOY\/002"]', 'TANJUNG PRIUK', '["on"]', '["on"]', NULL, NULL, '["KONTRAK\/001","KONTRAK\/002"]', '["HSO"]', '2018-04-18', '00:00:00', NULL, NULL, 'FO/001', NULL, '', 'single_port', '["50","50"]', NULL, NULL, NULL, NULL, '', NULL, NULL, '00:00:00', '2018-04-18', '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, '2018-04-17', '', 'no', 'no', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '567', '543', NULL, NULL, NULL, '-5.954545454545454', '-5.867256637168142', '', NULL, NULL, '2018-04-16', '00:00:00', '421', '', 'no', NULL, '-1.1849710982658959', '00:00:00', NULL, '100', '320', '', NULL, '2018-04-16', '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '421', '320', '0.2013888888888889', '765', NULL, '2018-04-20', '00:00:00', '', NULL, NULL, NULL, NULL, '654', NULL, '', NULL, '-3.022421524663677', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 11:34:53', NULL, NULL, 'admin', NULL, NULL, '65645', '432', '654', '344', '463', '230', NULL, '563', NULL, NULL, '876', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '112', NULL, NULL, '', '', NULL, NULL, '-5.954545454545454', '-5.867256637168142', '00:00:00', '00:00:00', '-1.1849710982658959', '410', NULL, NULL, '', '', '0.2013888888888889', '00:00:00', '00:00:00', '-3.022421524663677', '', '', 'Y', NULL, NULL, NULL, '["AGUS","INDRA"]', '""', '""', '""', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PELNI001', 0, '["CLIENT001","KONTRAK\/002"]', '34', '4523', '233', '665', '7856', '756', '776', '765', '345', '897', '754', '654', '765', '345', '643', '563', '123', '190', '567', '765', '678', '786', '321', '543', '542', '432', '120', '346', '113', '110', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (24, '', 'IWO/001', '["LOI\/001","LOI\/002"]', '["VOYAGE.001","VOY\/002"]', 'TANJUNG PRIUK', '["on"]', '["on"]', NULL, NULL, '["KONTRAK\/001","KONTRAK\/002"]', '["HSO"]', '2018-04-18', '00:00:00', NULL, NULL, 'FO/001', NULL, '', 'single_port', '["50","50"]', NULL, NULL, NULL, NULL, '', NULL, NULL, '00:00:00', '2018-04-18', '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, '2018-04-17', '', 'no', 'no', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '567', '543', NULL, NULL, NULL, '-Infinity', '-5.867256637168142', '', NULL, NULL, '1970-01-01', '00:00:00', '421', '', 'no', NULL, '-1.1849710982658959', '00:00:00', NULL, '100', '320', '', NULL, '2018-04-16', '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '421', '320', '0.2013888888888889', '765', NULL, '2018-04-20', '00:00:00', '', NULL, NULL, NULL, NULL, '654', NULL, '', NULL, '-3.022421524663677', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 10:36:11', NULL, NULL, 'admin', NULL, NULL, '65645', '432', '654', '344', '463', '230', NULL, '563', NULL, NULL, '876', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '112', NULL, NULL, '', '', NULL, NULL, '-Infinity', '-5.867256637168142', '00:00:00', '00:00:00', '-1.1849710982658959', '410', NULL, NULL, '', '', '0.2013888888888889', '00:00:00', '00:00:00', '-3.022421524663677', '', '', 'Y', NULL, NULL, NULL, '["AGUS","AGUS"]', '""', '""', '""', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PELNI001', 0, '["CLIENT001","KONTRAK\/002"]', '34', '4523', '233', '665', '7856', '756', '776', '765', '345', '897', '754', '654', '765', '345', '643', '563', '123', '190', '567', '765', '678', '786', '321', '543', '542', '432', '120', '346', '113', '', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (30, 'No Condition', 'IWO/001', '["LOI\/001","LOI\/002"]', '["VOYAGE\/001","VOY\/002"]', 'TANJUNG PRIUK', '["on"]', '["on"]', NULL, NULL, '["KONTRAK\/001","KONTRAK\/002"]', '["HSO"]', '2018-04-18', '00:00:00', NULL, NULL, 'FO/001', NULL, '', 'single_port', '["50","50"]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', '2018-04-18', '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, '2018-04-17', '', 'no', 'no', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '567', '543', NULL, NULL, NULL, '-5.954545454545454', '-5.867256637168142', '', NULL, NULL, '2018-04-16', '00:00:00', '421', '', 'no', NULL, '-1.1849710982658959', '00:00:00', NULL, '100', '320', NULL, NULL, '2018-04-16', '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '421', '320', '0.2013888888888889', '765', NULL, '2018-04-20', '00:00:00', '', NULL, NULL, NULL, NULL, '654', NULL, '', NULL, '-3.022421524663677', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 14:12:14', NULL, NULL, 'admin', NULL, NULL, '65645', '432', '654', '344', '463', '230', NULL, '563', NULL, NULL, '876', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '112', NULL, NULL, '', '', NULL, NULL, '-5.954545454545454', '-5.867256637168142', '00:00:00', '00:00:00', '-1.1849710982658959', '410', NULL, NULL, '', '', '0.2013888888888889', '00:00:00', '00:00:00', '-3.022421524663677', '', '', 'Y', NULL, NULL, NULL, '["AGUS","INDRA"]', '""', '""', '""', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PELNI001', 0, '["CLIENT001","KONTRAK\/002"]', '34', '4523', '233', '665', '7856', '756', '776', '765', '345', '897', '754', '654', '765', '345', '643', '563', '123', '190', '567', '765', '678', '786', '321', '543', '542', '432', '120', '346', '113', '110', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."FORM_ENTRY_FIELD" VALUES (31, 'No Condition', '', '["",""]', '["",""]', '', '["on"]', '["on"]', NULL, NULL, '["",""]', '[""]', NULL, '00:00:00', NULL, NULL, '', NULL, '', 'single_port', '["",""]', NULL, NULL, NULL, NULL, 'crude', NULL, NULL, '00:00:00', NULL, '00:00:00', NULL, NULL, '[""]', '110', 'multi_client', NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, 'single_product', NULL, NULL, NULL, NULL, NULL, '', 'no', 'no', '00:00:00', NULL, NULL, NULL, '2018-04-20', '', NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, '320', '102', '', '', NULL, NULL, NULL, '1', '1', '', NULL, NULL, NULL, '00:00:00', '', '', 'no', NULL, '1', '00:00:00', NULL, '100', '320', NULL, NULL, NULL, '', 14, NULL, NULL, '00:00:00', NULL, '00:00:00', '', '320', '1', '', NULL, NULL, '00:00:00', '', NULL, NULL, NULL, NULL, '', NULL, '', NULL, '1', '00:00:00', '00:00:00', '00:00:00', '00:00:00', NULL, NULL, NULL, '00:00:00', '200', '100', '00:00:00', '00:00:00', NULL, NULL, '200', NULL, NULL, '', '', '', '', '320', '210', NULL, NULL, '', '', '403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2018-04-16 14:20:00', NULL, NULL, 'admin', NULL, NULL, '', '', '', '', '', '230', NULL, '', NULL, NULL, '', NULL, NULL, '00:00:00', NULL, '', '432', '00:00:00', '', NULL, NULL, '', '', NULL, NULL, '1', '1', '00:00:00', '00:00:00', '1', '', NULL, NULL, '', '', '1', '00:00:00', '00:00:00', '1', '', '', 'Y', NULL, NULL, NULL, '["",""]', '""', '""', '""', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, '["",""]', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '321', '543', '542', '432', '120', '346', '113', '110', '432', '223', '543', '456', '123', '654', '110', '230', '234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- ----------------------------
-- Primary Key structure for table FORM_ENTRY_FIELD
-- ----------------------------
ALTER TABLE "public"."FORM_ENTRY_FIELD" ADD CONSTRAINT "FORM_ENTRY_FIELD_pkey" PRIMARY KEY ("ID");
